name: Continuos Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Build Docker image
    #   run: |
    #     docker-compose build
    - name: Get Git Pull
      run: |
        git pull origin

    - name: Run Docker containers
      run: |
        docker-compose up -d